### ISSUE TITLE
Clear date with custom way

### ISSUE THREAD

**Issue by jothikannan** [tonix-tuft/react-tempusdominus-bootstrap#1]
Hi,

Thanks for the nice component, I am trying to integrate this component on the project. I have a button to clear the selected date. I am using date property to update with my state values. But it doesn't get cleared. Can you please help me to fix it?

**Comment by tonix-tuft** [comment]
Hi @jothikannan,

OK. Can you provide me an example snippet so that I can see what you are trying to achieve? Thank you!

**Comment by tonix-tuft** [comment]
Hi @jothikannan Are you still facing the issue? Can you provide an example?

Otherwise I plan to close this issue in December. Thank you!

**Comment by tonix-tuft** [comment]
Closing. If it is still relevant, please, reopen this issue with a code snippet showing your use case so that I can take a look!

Cheers!
