### ISSUE TITLE
Conflict with Material-UI

### ISSUE THREAD

**Issue by GustavoSD** [tonix-tuft/react-tempusdominus-bootstrap#3]
This is super weird. This plugin has a serious problem with Material-Ui.

If I use ```<TimePicker />``` in a file that uses a Material-UI component, in this case ```<Button />```, ```<TimePicker />``` does not work as expected instead it looks and behaves as ```<DateTimePicker />```. But if I get rid of ```<Button />```, ```<TimePicker />``` works as expected.

This seems to affect ```<DateTimePicker />``` in general, because if use ```<DateTimePicker debug />``` in a file with a Material-UI button, it ignores the "debug" prop.

**Comment by tonix-tuft** [comment]
Hi @GustavoSD!

Thank you for your issue, please, could you provide some code examples showing your issue? (or even better a [codesandbox](https://codesandbox.io/s/new))

Thank you.

**Comment by GustavoSD** [comment]
@tonix-tuft Thanks for the quick response. I couldn't replicate the problem on codesandbox, but I was able to fix it with pickerRef and callback. 

Thanks for this amazing plugin.

**Comment by tonix-tuft** [comment]
@GustavoSD Great!

Would you mind sharing you experience here before I close the issue? Maybe just a code snippet that could help others facing the same issue as yours? That would be great ;)

Anyway, thank you.

**Comment by tonix-tuft** [comment]
@GustavoSD Also, don't forget to star this project if you find it useful! :)

**Comment by GustavoSD** [comment]
For those who may face this problem, I solved it this way: (based on Documentation)

```javascript
import React, { useEffect, useCallback, useRef } from 'react'
import moment from 'moment'

import { TimePickerBootstrapStyled } from '../styled'

const TimePickerBootstrap = ({ value, placeholder, onChange }) => {
    const pickerRef = useRef()

    useEffect(() => {
        pickerRef.current[0].children[0].value = value ? moment(value).format('h:mm A') : value
    }, [value])

    const callback = useCallback(() => {
        pickerRef.current.datetimepicker('defaultDate', value)
        pickerRef.current.datetimepicker('icons', { type: 'feather', up: 'chevron-up', down: 'chevron-down' })

        pickerRef.current[0].children[0].placeholder = placeholder
    }, [])

    const handleChange = ({ date, oldDate }) => {
        if (!oldDate) return
        onChange(date)
    }

    return <TimePickerBootstrapStyled pickerRef={pickerRef} callback={callback} onChange={handleChange} />
}

export default TimePickerBootstrap
```

- On ```const callback = useCallback(() => {})``` I added support for the placeholder
- Since onChange triggers on the first render, I added a validation on ```const handleChange() => {}```. If oldDate is different from null/undefined, that means the user changed the time on its own.
- I added a ```useEffect(() => {}, [])``` so each time the time changes the field gets updated. In my case it was a better option to set the time with DOM manipulation rather than with datetimepicker options because that would trigger the onChange event and then update the state in the component where I'm calling this TimePickerBootstrap component, and I don't want that to happen. That's the same reason I'm using defaultDate and not date.

**Comment by tonix-tuft** [comment]
Closing this issue.
