### ISSUE TITLE
Inline Date Picker

### ISSUE THREAD

**Issue by 67726e** [tonix-tuft/react-tempusdominus-bootstrap#4]
First, thanks for putting together this library. Saves me a good bit of headache!

I'm looking at the available API and I see a `DatePicker`, `TimePicker` and `DateTimePicker`, however the inline option is limited to `InlineDateTimePicker`. Is it possible to create an `InlineDatePicker` and `InlineTimePicker`, or is there some limitation of the underlying library?

**Comment by 67726e** [comment]
So, entirely possible, was able to write `<DatePicker inline />` similar to `InlineDateTimePicker` and with `<DateTimePicker inline />` - would you be open to my adding a PR for the `InlineDatePicker` and `InlineDateTimePicker` to round out the offering?

**Comment by tonix-tuft** [comment]
Hi @67726e!

thank you for being grateful for this library, I appreciate.

As you've seen, the `inline` parameter can be used with any component of this library besides `InlineDateTimePicker`.

Sure, you can send a PR if you want! Don't forget to update the documentation to reflect the new `InlineDatePicker ` as well as `InlineTimePicker` as well (or I will update the docs and examples myself).

Thank you!

**Comment by tonix-tuft** [comment]
Also, don't forget to star this library! 😄  Thank you!

**Comment by 67726e** [comment]
Finally put together a small PR to add convenience `Inline*` components to match the non-inline API, as to avoid future confusion for anyone using the library.

See: https://github.com/tonix-tuft/react-tempusdominus-bootstrap/pull/7

Of note, I am not sure how to create those nice little GIF previews you have for other components. Otherwise I've followed suite on the README.

**Comment by tonix-tuft** [comment]
Merged #7. Closing. Thank you!
